// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace SocrataSodaNet.Models
{
    public partial class HomePage
    {
        public IEnumerable<object> HomeMeta { get; set; }
        public IEnumerable<Asset> BannerImage { get; set; }
        public string Headline { get; set; }
        public string Bodycontent { get; set; }
        public string PageUrl { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}