// This code was generated by a cloud-generators-net tool 
// (see https://github.com/Kentico/cloud-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using KenticoCloud.Delivery;

namespace WebApplication.Models
{
    public partial class PageMetaMeta
    {
        public string PageTitle { get; set; }
        public string MetaDescription { get; set; }
        public string OpengraphTitle { get; set; }
        public string OpengraphDescription { get; set; }
        public IEnumerable<Asset> OpengraphImage { get; set; }
        public ContentItemSystemAttributes System { get; set; }
    }
}